# _config.yml
title: personal-page
email: your-email@example.com
description: >-
  personal web page of mine


#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
